version: '3.9'

services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: api
    restart: always
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    volumes:
      - .:/usr/src/app
    links:
      - database
    depends_on:
      - database
    # environment:
    #   - DB_COMPOSE_HOST=postgres

volumes:
  pgdata:
    driver: local
