name: CI

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install dependencies
        run: yarn

      # - name: Running Test
      #   run: yarn test

      - name: Build Application
        run: yarn build

      - name: Copy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASS}}
          # key: ${{secrets.SSH_KEY}}
          port: ${{secrets.SSH_PORT}}
          source: '., !node_modules, !src'
          target: '~/app/api'

      # - name: Install Packages Remote Server
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{secrets.SSH_HOST}}
      #     username: ${{secrets.SSH_USER}}
      #     password: ${{secrets.SSH_PASS}}
      #     # key: ${{secrets.SSH_KEY}}
      #     port: ${{secrets.SSH_PORT}}
      #     script: |
      #       cd ~/app/api
      #       npm install
      #       mpx run migration:run
      #     # script: |
      #     #   cd ~/app/api
      #     #   yarn
      #     #   yarn migration:run
      #     #   pm2 restart crud_api
